### ISSUE TITLE
Cannot create a new "inactive" project

### ISSUE THREAD

**Issue by TianweiXing** [msrivastava/labweb#4]
Trying to create a new project,  the "if active" box must be checked.

**Comment by TimeString** [comment]
Just want to describe the problem here in terms of RoR code, when we declare a binary (boolean) attribute and want to apply a validator on top of it, we should use `validates_inclusion_of:` instead of `validates:`. The following is _correct_:

```
validates_inclusion_of :useurlphoto, :in => [true, false], message: ": Missing photo source: by url or by uploading"
```

The following is _incorrect_:

```
validates :isactive, presence: {message: ": Missing active/nonactive status"}
```
